name: first-job
on: [push]
jobs:
 print-hello-world:
  runs-on: ubuntu-latest
  steps:
    - run: echo "hello world"
    - run: echo "how are you"
 print-hello-world-2:
   runs-on: ubuntu-latest
   steps:
    - run: echo "hello world"
    - run: echo "how are you"
 tree-job:
   runs-on: ubuntu-latest
   steps:
    - name: test-job-step-1
      uses: actions/checkout@v2
    - name: test-job-step-2
      run: tree
   
   
