name: first-job
on: [push]
jobs:
 tree-job:
   runs-on: ubuntu-latest
   steps:
    - name: test-job-step-1
      uses: actions/checkout@v2
    - name: test-job-step-2
      run: tree
 build-project:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install nodejs
      uses: actions/setup-node@v2
      with:
       node-version: "17.0.0"
    - name: Install deps
      run: yarn
    - name: Build the project
      run: yarn build
    - name: Deploy the project
      env:
       VERCEL_PROJECT_ID: prj_JMwYXVj3FhXC7s8F9BGzz4Nfk0Rk
       VERCEL_ORG_ID: uppGr9DlNxrPctgJtszJYVMu
      run: yarn run deploy
    - name: Completion
      run: echo "Done!"
   
   
