name: first-job
on: [push]
jobs:
 treeJob:
   runs-on: ubuntu-latest
   outputs:
    text: ${{ steps.complete.outputs.var1 }}
   steps:
    - name: test-job-step-1
      uses: actions/checkout@v2
    - name: test-job-step-2
      run: tree
    - name: Setup complete
      id: complete
      run: echo "::set-output name=var1::my name is var1"
 test-job:
  needs: tree-job
  runs-on: ubuntu-latest
  env:
   MY_VARIABLE: ${{ needs.treeJob.outputs.text}}
  steps:
   - run: echo "YOLOoo $MY_VARIABLE"
 build-project:
   runs-on: ubuntu-latest
   env:
       VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
       VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
       VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN}}
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install nodejs
      uses: actions/setup-node@v2
      with:
       node-version: "17.0.0"
    - name: Install deps
      run: yarn
    - name: Build the project
      run: yarn build
    - name: Deploy the project
      run: yarn run deploy
    - name: Completion
      run: echo "Done!"
   
   
