name: first-job
on: [push]
jobs:
 tree-job:
   runs-on: ubuntu-latest
   steps:
    - name: test-job-step-1
      uses: actions/checkout@v2
    - name: test-job-step-2
      run: tree
 test-job:
  needs: tree-job
  runs-on: ubuntu-latest
  steps:
   - run: echo "YOLOoo"
 build-project:
   runs-on: ubuntu-latest
   env:
       VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
       VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
       VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN}}
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install nodejs
      uses: actions/setup-node@v2
      with:
       node-version: "17.0.0"
    - name: Install deps
      run: yarn
    - name: Build the project
      run: yarn build
    - name: Deploy the project
      run: yarn run deploy
    - name: Completion
      run: echo "Done!"
   
   
