name: first-job
on: [push]
jobs:
 print-hello-world:
  runs-on: ubuntu-latest
  steps:
    - run: echo "hello world"
    - run: echo "how are you"
 tree-job:
   runs-on: ubuntu-latest
   steps:
    - name: test-job-step-1
      uses: actions/checkout@v2
    - name: test-job-step-2
      run: tree
  build-project:
   runs-on: ubuntu-latest
   steps:
    - name: Install nodejs
      uses: actions/setup-node@v2
      with:
       node-version: "14.17.0"
    - name: Install deps
      run: yarn
    - name: Build the project
      run: yarn build
    - name: Completion
      run: echo "Done!"
   
   
